<?php

namespace ContainerQ5aSoum;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_McSevCdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.McSevCd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.McSevCd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenement' => ['privates', '.errored..service_locator.McSevCd.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.McSevCd": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'programmeRepository' => ['privates', 'App\\Repository\\ProgrammeRepository', 'getProgrammeRepositoryService', true],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'programmeRepository' => 'App\\Repository\\ProgrammeRepository',
        ]);
    }
}
