<?php

namespace ContainerQ5aSoum;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementControllerajouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kWc6mvO.App\Controller\Admin\EvenementController::ajouter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kWc6mvO.App\\Controller\\Admin\\EvenementController::ajouter()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\Admin\\EvenementController::ajouter()', $container);
    }
}
