<?php

namespace ContainerQ5aSoum;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspaceControllerlisteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kDTWo6B.App\Controller\Admin\EspaceController::liste()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kDTWo6B.App\\Controller\\Admin\\EspaceController::liste()'] = ($container->privates['.service_locator.kDTWo6B'] ?? $container->load('get_ServiceLocator_KDTWo6BService'))->withContext('App\\Controller\\Admin\\EspaceController::liste()', $container);
    }
}
