<?php

namespace ContainerQ5aSoum;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aJoVYSb.App\Controller\Front\feedbackController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.aJoVYSb'] ?? $container->load('get_ServiceLocator_AJoVYSbService'));

        if (isset($container->privates['.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::delete()'])) {
            return $container->privates['.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::delete()'];
        }

        return $container->privates['.service_locator.aJoVYSb.App\\Controller\\Front\\feedbackController::delete()'] = $a->withContext('App\\Controller\\Front\\feedbackController::delete()', $container);
    }
}
