<?php

namespace ContainerQ5aSoum;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammeControllerlisteProgrammesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.McSevCd.App\Controller\Admin\ProgrammeController::listeProgrammes()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.McSevCd.App\\Controller\\Admin\\ProgrammeController::listeProgrammes()'] = ($container->privates['.service_locator.McSevCd'] ?? $container->load('get_ServiceLocator_McSevCdService'))->withContext('App\\Controller\\Admin\\ProgrammeController::listeProgrammes()', $container);
    }
}
