<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AJoVYSbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aJoVYSb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aJoVYSb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedback' => ['privates', '.errored..service_locator.aJoVYSb.App\\Entity\\Feedback', NULL, 'Cannot autowire service ".service_locator.aJoVYSb": it needs an instance of "App\\Entity\\Feedback" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'feedback' => 'App\\Entity\\Feedback',
            'entityManager' => '?',
        ]);
    }
}
