<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementControllerlisteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uaK11Lb.App\Controller\Admin\EvenementController::liste()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uaK11Lb.App\\Controller\\Admin\\EvenementController::liste()'] = ($container->privates['.service_locator.uaK11Lb'] ?? $container->load('get_ServiceLocator_UaK11LbService'))->withContext('App\\Controller\\Admin\\EvenementController::liste()', $container);
    }
}
