<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspacesControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rzT29Ys.App\Controller\Front\EspacesController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rzT29Ys.App\\Controller\\Front\\EspacesController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espace' => ['privates', '.errored..service_locator.rzT29Ys.App\\Entity\\Espace', NULL, 'Cannot autowire service ".service_locator.rzT29Ys": it needs an instance of "App\\Entity\\Espace" but this type has been excluded in "config/services.yaml".'],
        ], [
            'espace' => 'App\\Entity\\Espace',
        ]))->withContext('App\\Controller\\Front\\EspacesController::detail()', $container);
    }
}
