<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspaceControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wQ.bJkn.App\Controller\Admin\EspaceController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQ.bJkn.App\\Controller\\Admin\\EspaceController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espace' => ['privates', '.errored..service_locator.wQ.bJkn.App\\Entity\\Espace', NULL, 'Cannot autowire service ".service_locator.wQ.bJkn": it needs an instance of "App\\Entity\\Espace" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'espace' => 'App\\Entity\\Espace',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\EspaceController::delete()', $container);
    }
}
