<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.scb.0A3.App\Controller\Front\eventsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.scb.0A3.App\\Controller\\Front\\eventsController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.scb.0A3.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.scb.0A3": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'programmeRepository' => ['privates', 'App\\Repository\\ProgrammeRepository', 'getProgrammeRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Evenement',
            'programmeRepository' => 'App\\Repository\\ProgrammeRepository',
        ]))->withContext('App\\Controller\\Front\\eventsController::show()', $container);
    }
}
