<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspace2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rzT29Ys.App\Entity\Espace' shared service.
     *
     * @return \App\Entity\Espace
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rzT29Ys": it needs an instance of "App\\Entity\\Espace" but this type has been excluded in "config/services.yaml".');
    }
}
