<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dD8aLsL.App\Controller\Front\feedbackController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dD8aLsL.App\\Controller\\Front\\feedbackController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackRepo' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
        ], [
            'feedbackRepo' => 'App\\Repository\\FeedbackRepository',
        ]))->withContext('App\\Controller\\Front\\feedbackController::index()', $container);
    }
}
