<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aJoVYSb.App\Entity\Feedback' shared service.
     *
     * @return \App\Entity\Feedback
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aJoVYSb": it needs an instance of "App\\Entity\\Feedback" but this type has been excluded in "config/services.yaml".');
    }
}
