<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BTmbWK6.App\Controller\Admin\ProgrammeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::delete()'] = ($container->privates['.service_locator.BTmbWK6'] ?? $container->load('get_ServiceLocator_BTmbWK6Service'))->withContext('App\\Controller\\Admin\\ProgrammeController::delete()', $container);
    }
}
