<?php

namespace ContainerHjwQW5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BTmbWK6.App\Controller\Admin\ProgrammeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.BTmbWK6'] ?? $container->load('get_ServiceLocator_BTmbWK6Service'));

        if (isset($container->privates['.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::edit()'])) {
            return $container->privates['.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::edit()'];
        }

        return $container->privates['.service_locator.BTmbWK6.App\\Controller\\Admin\\ProgrammeController::edit()'] = $a->withContext('App\\Controller\\Admin\\ProgrammeController::edit()', $container);
    }
}
