<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjwQW5t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjwQW5t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHjwQW5t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHjwQW5t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHjwQW5t\App_KernelDevDebugContainer([
    'container.build_hash' => 'HjwQW5t',
    'container.build_id' => 'b83a4cf2',
    'container.build_time' => 1744801212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjwQW5t');
